### ISSUE TITLE
PA review - Auth

### ISSUE THREAD

**Issue by clustermass** [clustermass/cookhouse_stories#2]
Andy, please review my first MVP - Auth.
https://cookhouse-stories.herokuapp.com/

**Comment by andywynkoop** [comment]
Looks great so far! Here are a few changes you should make:
- [x] Errors should be on their own lines and printed without quotes or commas
- [x] Where you have `I don’t have an account.  Sign-up!` and `I already have an account.` You should put the spaces after the period but not within the title of the link so that the underline starts with the word instead of with the leading spaces.
- [x] Log in prompts the user for a username and password, but expects an email in order to log in successfully - change the field's placeholder to say email instead.
- [x] The log in and sign up modals should be forms with a onSubmit handler. I should be able to press `enter` after entering credentials and have the form do its submit action.
- [x] Visiting a random route should redirect home or render a 404 page.
- [x] Add `cursor: pointer` styling to all buttons/links that are/look clickable including form submit buttons in session modals.

Overall, it looks really good the styling and modals look just like the original site. Keep up the good work

**Comment by clustermass** [comment]
Somehow my custom fonts didn't got uploaded.

**Comment by andywynkoop** [comment]
How are you trying to include them? google api?
